# Generated by Django 4.2.3 on 2023-08-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_revokedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizuser',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
