# Generated by Django 4.2.3 on 2023-08-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_quizuser_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizuser',
            name='deleted',
        ),
    ]
