# Generated by Django 4.2.3 on 2023-08-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_quizuser_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
